card_name:
  db:
    - 东楼经理室
    - 变电站技术室
    - 西楼调控房
    - 西楼监视室
    - 售票办公室
    - 军营保管室
    - 设备领用室
    - 水泥厂宿舍201
    - 中心贵宾室
    - 水泥厂办公室
    - 地下通道钥匙
    - 西楼医务室
    - 变电站宿舍
    - 实验楼资料室
    - 战壕标准
  cg:
    - 酒店国王房
    - 雷达站无人机平台
    - 酒店王子房
    - 雷达站数据中心
    - 实验楼资料室
    - 酒店黑桃房
    - 雷达站控制室
    - 实验楼办公室
    - 酒店将军房
    - 酒店方片房
    - 小镇餐厅
    - 运输机会议室

  ht:
    - 总裁室会客厅
    - 东区吊桥
    - 黑市服务器室
    - 蓝室核心
    - 蓝室玻璃房
    - 蓝室数据中心
    - 组装车间二楼实验室
    - 西区大门
    - 员工通道
    - 3号宿舍里屋
    - 中控室三楼
    - 浮力室衣物间

  bks:
    - 地下金库储藏间
    - 总裁会议室
    - 旅店用餐间
    - Relink植入手术室
    - 博物馆展厅套件
    - 老浴场贵宾室
    - 医疗会议室
    - 博物馆废弃展厅
    - 1号审讯室
    - 生物数据机房
    - 海洋检测厅
    - 老浴场餐厅
    - 门诊室
    - 旅店员工休息室
    - 博物馆监控室
    - 东城民宅卧室
    - 巴别塔供电权限卡
    - 西城民宅卧室

coordinate_position2:
  standard_screen_pixel: [2560, 1440]
  card_region: [583, 208]
  card_pixel: [625, 212]
  name_pixel: [178, 27]
  price_region: [2184, 1172]
  price_pixel: [116, 23]
  wallet_region: [2204, 60]
  wallet_pixel: [80, 20]
  
coordinate_position:
 standard_screen_pixel: [1920, 1080]
 card_region: [437, 156]
 card_pixel: [469, 159]
 name_pixel: [134, 20]
 price_region: [1638, 879]
 price_pixel: [87, 17]
 wallet_region: [1653, 45]
 wallet_pixel: [60, 15]
    